name: advanced_nacl
channels:
  - conda-forge
  - defaults
dependencies:
  - openmm
  - scikit-learn
  - jupyterlab
  - ipympl
  - nglview
  - matplotlib 
	- MDAnalysis
	- numpy
	- pickle
	- mdanalysistests
